import 'styles/globals.css'

import type { AppProps } from 'next/app'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>Asana Clone</title>
                <meta name="title" content='Create Next App' key="title" />
                <meta name="description" content='Generated by create next app' key="description" />
            </Head>
            <Component {...pageProps} />
        </>
    )
}