import type { FC } from "react";
import Head from "next/head";

const HeadSEO: FC = () => {
    return (
        <Head>
            <title>Asana Clone</title>
            <meta name="title" content='Create Next App' key="title" />
            <meta name="description" content='Generated by create next app' key="description" />
        </Head>
    )
}

export default HeadSEO